### PR TITLE
fixed issue with handles not being initialized (i think)

### PR DESCRIPTION
**Pull request by veygax**
i mean, it doesn't crash anymore, and the logs say they all initialized successfully soo

### CODE REVIEW

**Comment by veygax** [comment]
c# is hard

**Comment by FragileDeviations** [comment]
the logging 😭

**Comment by veygax** [comment]
Yeah lol, I got fed up with it lol, I'll probably add some #if DEBUG statements into it.

**Comment by veygax** [comment]
fixed

**Comment by adamd3v** [comment]
was this tested

**Comment by veygax** [comment]
> was this tested

Yeah, it stopped the crash for me

**Comment by veygax** [comment]
new patch

**Pull request closed without merging**
